defaults: &defaults
  from: 'hello@climates.com'
  cc: 'ben@montfort.io'
  domain: localhost
  google_apps:
    client_id: 269899364614-hm3nsrooe2t34j0p53ej17kqop9efbtd.apps.googleusercontent.com
    secret: RkSiCrAYLUAIOdaIGlwgEYYy
    domain: gmail.com
  slack:
    webhook_url: <%= ENV['SLACK_WEBHOOK_URL'] %>
    default_channel: <%= ENV['SLACK_DEFAULT_CHANNEL'] %>
  enabled_notifications: ['slack']

development:
  <<: *defaults

test:
 <<: *defaults
 enabled_notifications: []

production:
  <<: *defaults
  from: <%= ENV['POSTMARK_FROM'] %>
  cc: <%= ENV['DEFAULT_CC'] %>
  postmark:
    api_key: <%= ENV['POSTMARK_API_KEY'] %>
  domain: <%= ENV['APP_DOMAIN'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
